name: Continuous integration

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    branches:
      - '**'

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [release-3_16, release-3_22, latest]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test on QGIS
        run: docker-compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run-docker-tests.sh
      - name: Test on QGIS with PG
        run: docker-compose -f .docker/docker-compose.gh.yml run -e "PGHOST=postgres11" qgis /usr/src/.docker/run-docker-tests.sh
